#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOESBUS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SHOESSS")]
	public partial class Shoes2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHI_TIET_HOA_DON(CHI_TIET_HOA_DON instance);
    partial void UpdateCHI_TIET_HOA_DON(CHI_TIET_HOA_DON instance);
    partial void DeleteCHI_TIET_HOA_DON(CHI_TIET_HOA_DON instance);
    partial void InsertCHI_TIET_MAT_HANG(CHI_TIET_MAT_HANG instance);
    partial void UpdateCHI_TIET_MAT_HANG(CHI_TIET_MAT_HANG instance);
    partial void DeleteCHI_TIET_MAT_HANG(CHI_TIET_MAT_HANG instance);
    partial void InsertDANH_SACH_HOA_DON_CHO(DANH_SACH_HOA_DON_CHO instance);
    partial void UpdateDANH_SACH_HOA_DON_CHO(DANH_SACH_HOA_DON_CHO instance);
    partial void DeleteDANH_SACH_HOA_DON_CHO(DANH_SACH_HOA_DON_CHO instance);
    partial void InsertDANH_SACH_KY_GUI_CHO(DANH_SACH_KY_GUI_CHO instance);
    partial void UpdateDANH_SACH_KY_GUI_CHO(DANH_SACH_KY_GUI_CHO instance);
    partial void DeleteDANH_SACH_KY_GUI_CHO(DANH_SACH_KY_GUI_CHO instance);
    partial void InsertGIO_HANG(GIO_HANG instance);
    partial void UpdateGIO_HANG(GIO_HANG instance);
    partial void DeleteGIO_HANG(GIO_HANG instance);
    partial void InsertHOA_DON(HOA_DON instance);
    partial void UpdateHOA_DON(HOA_DON instance);
    partial void DeleteHOA_DON(HOA_DON instance);
    partial void InsertKHACH_HANG(KHACH_HANG instance);
    partial void UpdateKHACH_HANG(KHACH_HANG instance);
    partial void DeleteKHACH_HANG(KHACH_HANG instance);
    partial void InsertKY_GUI(KY_GUI instance);
    partial void UpdateKY_GUI(KY_GUI instance);
    partial void DeleteKY_GUI(KY_GUI instance);
    partial void InsertMAT_HANG(MAT_HANG instance);
    partial void UpdateMAT_HANG(MAT_HANG instance);
    partial void DeleteMAT_HANG(MAT_HANG instance);
    partial void InsertNHAN_VIEN(NHAN_VIEN instance);
    partial void UpdateNHAN_VIEN(NHAN_VIEN instance);
    partial void DeleteNHAN_VIEN(NHAN_VIEN instance);
    partial void InsertPAYPAL(PAYPAL instance);
    partial void UpdatePAYPAL(PAYPAL instance);
    partial void DeletePAYPAL(PAYPAL instance);
    #endregion
		
		public Shoes2DataContext() : 
				base(global::SHOESBUS.Properties.Settings.Default.SHOESSSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Shoes2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Shoes2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Shoes2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Shoes2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHI_TIET_HOA_DON> CHI_TIET_HOA_DONs
		{
			get
			{
				return this.GetTable<CHI_TIET_HOA_DON>();
			}
		}
		
		public System.Data.Linq.Table<CHI_TIET_MAT_HANG> CHI_TIET_MAT_HANGs
		{
			get
			{
				return this.GetTable<CHI_TIET_MAT_HANG>();
			}
		}
		
		public System.Data.Linq.Table<DANH_SACH_HOA_DON_CHO> DANH_SACH_HOA_DON_CHOs
		{
			get
			{
				return this.GetTable<DANH_SACH_HOA_DON_CHO>();
			}
		}
		
		public System.Data.Linq.Table<DANH_SACH_KY_GUI_CHO> DANH_SACH_KY_GUI_CHOs
		{
			get
			{
				return this.GetTable<DANH_SACH_KY_GUI_CHO>();
			}
		}
		
		public System.Data.Linq.Table<GIO_HANG> GIO_HANGs
		{
			get
			{
				return this.GetTable<GIO_HANG>();
			}
		}
		
		public System.Data.Linq.Table<HOA_DON> HOA_DONs
		{
			get
			{
				return this.GetTable<HOA_DON>();
			}
		}
		
		public System.Data.Linq.Table<KHACH_HANG> KHACH_HANGs
		{
			get
			{
				return this.GetTable<KHACH_HANG>();
			}
		}
		
		public System.Data.Linq.Table<KY_GUI> KY_GUIs
		{
			get
			{
				return this.GetTable<KY_GUI>();
			}
		}
		
		public System.Data.Linq.Table<MAT_HANG> MAT_HANGs
		{
			get
			{
				return this.GetTable<MAT_HANG>();
			}
		}
		
		public System.Data.Linq.Table<NHAN_VIEN> NHAN_VIENs
		{
			get
			{
				return this.GetTable<NHAN_VIEN>();
			}
		}
		
		public System.Data.Linq.Table<PAYPAL> PAYPALs
		{
			get
			{
				return this.GetTable<PAYPAL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHI_TIET_HOA_DON")]
	public partial class CHI_TIET_HOA_DON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoaDon;
		
		private string _MaKhachHang;
		
		private string _MaNhanVien;
		
		private double _SoLuong;
		
		private string _Size;
		
		private System.DateTime _NgayThanhToan;
		
		private string _DanhGia;
		
		private EntityRef<HOA_DON> _HOA_DON;
		
		private EntityRef<KHACH_HANG> _KHACH_HANG;
		
		private EntityRef<NHAN_VIEN> _NHAN_VIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(string value);
    partial void OnMaHoaDonChanged();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnSoLuongChanging(double value);
    partial void OnSoLuongChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    partial void OnNgayThanhToanChanging(System.DateTime value);
    partial void OnNgayThanhToanChanged();
    partial void OnDanhGiaChanging(string value);
    partial void OnDanhGiaChanged();
    #endregion
		
		public CHI_TIET_HOA_DON()
		{
			this._HOA_DON = default(EntityRef<HOA_DON>);
			this._KHACH_HANG = default(EntityRef<KHACH_HANG>);
			this._NHAN_VIEN = default(EntityRef<NHAN_VIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					if (this._HOA_DON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Char(20)")]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KHACH_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="Char(20)")]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NHAN_VIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Float NOT NULL")]
		public double SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="Char(53) NOT NULL", CanBeNull=false)]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThanhToan", DbType="Date NOT NULL")]
		public System.DateTime NgayThanhToan
		{
			get
			{
				return this._NgayThanhToan;
			}
			set
			{
				if ((this._NgayThanhToan != value))
				{
					this.OnNgayThanhToanChanging(value);
					this.SendPropertyChanging();
					this._NgayThanhToan = value;
					this.SendPropertyChanged("NgayThanhToan");
					this.OnNgayThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhGia", DbType="NVarChar(2000)")]
		public string DanhGia
		{
			get
			{
				return this._DanhGia;
			}
			set
			{
				if ((this._DanhGia != value))
				{
					this.OnDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._DanhGia = value;
					this.SendPropertyChanged("DanhGia");
					this.OnDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOA_DON_CHI_TIET_HOA_DON", Storage="_HOA_DON", ThisKey="MaHoaDon", OtherKey="MaHoaDon", IsForeignKey=true)]
		public HOA_DON HOA_DON
		{
			get
			{
				return this._HOA_DON.Entity;
			}
			set
			{
				HOA_DON previousValue = this._HOA_DON.Entity;
				if (((previousValue != value) 
							|| (this._HOA_DON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOA_DON.Entity = null;
						previousValue.CHI_TIET_HOA_DON = null;
					}
					this._HOA_DON.Entity = value;
					if ((value != null))
					{
						value.CHI_TIET_HOA_DON = this;
						this._MaHoaDon = value.MaHoaDon;
					}
					else
					{
						this._MaHoaDon = default(string);
					}
					this.SendPropertyChanged("HOA_DON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_CHI_TIET_HOA_DON", Storage="_KHACH_HANG", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KHACH_HANG KHACH_HANG
		{
			get
			{
				return this._KHACH_HANG.Entity;
			}
			set
			{
				KHACH_HANG previousValue = this._KHACH_HANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACH_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACH_HANG.Entity = null;
						previousValue.CHI_TIET_HOA_DONs.Remove(this);
					}
					this._KHACH_HANG.Entity = value;
					if ((value != null))
					{
						value.CHI_TIET_HOA_DONs.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("KHACH_HANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHAN_VIEN_CHI_TIET_HOA_DON", Storage="_NHAN_VIEN", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NHAN_VIEN NHAN_VIEN
		{
			get
			{
				return this._NHAN_VIEN.Entity;
			}
			set
			{
				NHAN_VIEN previousValue = this._NHAN_VIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHAN_VIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHAN_VIEN.Entity = null;
						previousValue.CHI_TIET_HOA_DONs.Remove(this);
					}
					this._NHAN_VIEN.Entity = value;
					if ((value != null))
					{
						value.CHI_TIET_HOA_DONs.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("NHAN_VIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHI_TIET_MAT_HANG")]
	public partial class CHI_TIET_MAT_HANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGiay;
		
		private double _DonGiaNhap;
		
		private string _ChatLieu;
		
		private string _BaoHanh;
		
		private string _DieuKien;
		
		private string _GhiChu;
		
		private EntityRef<MAT_HANG> _MAT_HANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGiayChanging(string value);
    partial void OnMaGiayChanged();
    partial void OnDonGiaNhapChanging(double value);
    partial void OnDonGiaNhapChanged();
    partial void OnChatLieuChanging(string value);
    partial void OnChatLieuChanged();
    partial void OnBaoHanhChanging(string value);
    partial void OnBaoHanhChanged();
    partial void OnDieuKienChanging(string value);
    partial void OnDieuKienChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public CHI_TIET_MAT_HANG()
		{
			this._MAT_HANG = default(EntityRef<MAT_HANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiay", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGiay
		{
			get
			{
				return this._MaGiay;
			}
			set
			{
				if ((this._MaGiay != value))
				{
					if (this._MAT_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGiayChanging(value);
					this.SendPropertyChanging();
					this._MaGiay = value;
					this.SendPropertyChanged("MaGiay");
					this.OnMaGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaNhap", DbType="Float NOT NULL")]
		public double DonGiaNhap
		{
			get
			{
				return this._DonGiaNhap;
			}
			set
			{
				if ((this._DonGiaNhap != value))
				{
					this.OnDonGiaNhapChanging(value);
					this.SendPropertyChanging();
					this._DonGiaNhap = value;
					this.SendPropertyChanged("DonGiaNhap");
					this.OnDonGiaNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChatLieu", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string ChatLieu
		{
			get
			{
				return this._ChatLieu;
			}
			set
			{
				if ((this._ChatLieu != value))
				{
					this.OnChatLieuChanging(value);
					this.SendPropertyChanging();
					this._ChatLieu = value;
					this.SendPropertyChanged("ChatLieu");
					this.OnChatLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaoHanh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BaoHanh
		{
			get
			{
				return this._BaoHanh;
			}
			set
			{
				if ((this._BaoHanh != value))
				{
					this.OnBaoHanhChanging(value);
					this.SendPropertyChanging();
					this._BaoHanh = value;
					this.SendPropertyChanged("BaoHanh");
					this.OnBaoHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DieuKien", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string DieuKien
		{
			get
			{
				return this._DieuKien;
			}
			set
			{
				if ((this._DieuKien != value))
				{
					this.OnDieuKienChanging(value);
					this.SendPropertyChanging();
					this._DieuKien = value;
					this.SendPropertyChanged("DieuKien");
					this.OnDieuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(2000)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAT_HANG_CHI_TIET_MAT_HANG", Storage="_MAT_HANG", ThisKey="MaGiay", OtherKey="MaGiay", IsForeignKey=true)]
		public MAT_HANG MAT_HANG
		{
			get
			{
				return this._MAT_HANG.Entity;
			}
			set
			{
				MAT_HANG previousValue = this._MAT_HANG.Entity;
				if (((previousValue != value) 
							|| (this._MAT_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAT_HANG.Entity = null;
						previousValue.CHI_TIET_MAT_HANG = null;
					}
					this._MAT_HANG.Entity = value;
					if ((value != null))
					{
						value.CHI_TIET_MAT_HANG = this;
						this._MaGiay = value.MaGiay;
					}
					else
					{
						this._MaGiay = default(string);
					}
					this.SendPropertyChanged("MAT_HANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANH_SACH_HOA_DON_CHO")]
	public partial class DANH_SACH_HOA_DON_CHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoaDon;
		
		private string _MaKhachHang;
		
		private string _MaGiay;
		
		private string _MaKhuyenMai;
		
		private string _PhuongThucThanhToan;
		
		private double _DonGiaBan;
		
		private string _KhuyenMai;
		
		private double _ThanhTien;
		
		private double _SoLuong;
		
		private string _Size;
		
		private System.DateTime _NgayThanhToan;
		
		private EntityRef<KHACH_HANG> _KHACH_HANG;
		
		private EntityRef<MAT_HANG> _MAT_HANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(string value);
    partial void OnMaHoaDonChanged();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnMaGiayChanging(string value);
    partial void OnMaGiayChanged();
    partial void OnMaKhuyenMaiChanging(string value);
    partial void OnMaKhuyenMaiChanged();
    partial void OnPhuongThucThanhToanChanging(string value);
    partial void OnPhuongThucThanhToanChanged();
    partial void OnDonGiaBanChanging(double value);
    partial void OnDonGiaBanChanged();
    partial void OnKhuyenMaiChanging(string value);
    partial void OnKhuyenMaiChanged();
    partial void OnThanhTienChanging(double value);
    partial void OnThanhTienChanged();
    partial void OnSoLuongChanging(double value);
    partial void OnSoLuongChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    partial void OnNgayThanhToanChanging(System.DateTime value);
    partial void OnNgayThanhToanChanged();
    #endregion
		
		public DANH_SACH_HOA_DON_CHO()
		{
			this._KHACH_HANG = default(EntityRef<KHACH_HANG>);
			this._MAT_HANG = default(EntityRef<MAT_HANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Char(20)")]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KHACH_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiay", DbType="Char(20)")]
		public string MaGiay
		{
			get
			{
				return this._MaGiay;
			}
			set
			{
				if ((this._MaGiay != value))
				{
					if (this._MAT_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGiayChanging(value);
					this.SendPropertyChanging();
					this._MaGiay = value;
					this.SendPropertyChanged("MaGiay");
					this.OnMaGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhuyenMai", DbType="Char(20)")]
		public string MaKhuyenMai
		{
			get
			{
				return this._MaKhuyenMai;
			}
			set
			{
				if ((this._MaKhuyenMai != value))
				{
					this.OnMaKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._MaKhuyenMai = value;
					this.SendPropertyChanged("MaKhuyenMai");
					this.OnMaKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongThucThanhToan", DbType="NChar(20)")]
		public string PhuongThucThanhToan
		{
			get
			{
				return this._PhuongThucThanhToan;
			}
			set
			{
				if ((this._PhuongThucThanhToan != value))
				{
					this.OnPhuongThucThanhToanChanging(value);
					this.SendPropertyChanging();
					this._PhuongThucThanhToan = value;
					this.SendPropertyChanged("PhuongThucThanhToan");
					this.OnPhuongThucThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaBan", DbType="Float NOT NULL")]
		public double DonGiaBan
		{
			get
			{
				return this._DonGiaBan;
			}
			set
			{
				if ((this._DonGiaBan != value))
				{
					this.OnDonGiaBanChanging(value);
					this.SendPropertyChanging();
					this._DonGiaBan = value;
					this.SendPropertyChanged("DonGiaBan");
					this.OnDonGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhuyenMai", DbType="Char(53) NOT NULL", CanBeNull=false)]
		public string KhuyenMai
		{
			get
			{
				return this._KhuyenMai;
			}
			set
			{
				if ((this._KhuyenMai != value))
				{
					this.OnKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._KhuyenMai = value;
					this.SendPropertyChanged("KhuyenMai");
					this.OnKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Float NOT NULL")]
		public double ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Float NOT NULL")]
		public double SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="Char(53) NOT NULL", CanBeNull=false)]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThanhToan", DbType="Date NOT NULL")]
		public System.DateTime NgayThanhToan
		{
			get
			{
				return this._NgayThanhToan;
			}
			set
			{
				if ((this._NgayThanhToan != value))
				{
					this.OnNgayThanhToanChanging(value);
					this.SendPropertyChanging();
					this._NgayThanhToan = value;
					this.SendPropertyChanged("NgayThanhToan");
					this.OnNgayThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_DANH_SACH_HOA_DON_CHO", Storage="_KHACH_HANG", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KHACH_HANG KHACH_HANG
		{
			get
			{
				return this._KHACH_HANG.Entity;
			}
			set
			{
				KHACH_HANG previousValue = this._KHACH_HANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACH_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACH_HANG.Entity = null;
						previousValue.DANH_SACH_HOA_DON_CHOs.Remove(this);
					}
					this._KHACH_HANG.Entity = value;
					if ((value != null))
					{
						value.DANH_SACH_HOA_DON_CHOs.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("KHACH_HANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAT_HANG_DANH_SACH_HOA_DON_CHO", Storage="_MAT_HANG", ThisKey="MaGiay", OtherKey="MaGiay", IsForeignKey=true)]
		public MAT_HANG MAT_HANG
		{
			get
			{
				return this._MAT_HANG.Entity;
			}
			set
			{
				MAT_HANG previousValue = this._MAT_HANG.Entity;
				if (((previousValue != value) 
							|| (this._MAT_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAT_HANG.Entity = null;
						previousValue.DANH_SACH_HOA_DON_CHOs.Remove(this);
					}
					this._MAT_HANG.Entity = value;
					if ((value != null))
					{
						value.DANH_SACH_HOA_DON_CHOs.Add(this);
						this._MaGiay = value.MaGiay;
					}
					else
					{
						this._MaGiay = default(string);
					}
					this.SendPropertyChanged("MAT_HANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANH_SACH_KY_GUI_CHO")]
	public partial class DANH_SACH_KY_GUI_CHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhachHang;
		
		private string _TenGiay;
		
		private System.Data.Linq.Binary _Anh1;
		
		private System.Data.Linq.Binary _Anh2;
		
		private System.Data.Linq.Binary _Anh3;
		
		private System.Data.Linq.Binary _Anh4;
		
		private double _SoLuong;
		
		private string _MauSac;
		
		private string _Size;
		
		private string _ChatLieu;
		
		private string _BaoHanh;
		
		private string _DieuKien;
		
		private string _GhiChu;
		
		private System.DateTime _NgayKyGui;
		
		private string _ThoiGianGui;
		
		private double _PhiKyGui;
		
		private double _DonGiaNhap;
		
		private EntityRef<KHACH_HANG> _KHACH_HANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnTenGiayChanging(string value);
    partial void OnTenGiayChanged();
    partial void OnAnh1Changing(System.Data.Linq.Binary value);
    partial void OnAnh1Changed();
    partial void OnAnh2Changing(System.Data.Linq.Binary value);
    partial void OnAnh2Changed();
    partial void OnAnh3Changing(System.Data.Linq.Binary value);
    partial void OnAnh3Changed();
    partial void OnAnh4Changing(System.Data.Linq.Binary value);
    partial void OnAnh4Changed();
    partial void OnSoLuongChanging(double value);
    partial void OnSoLuongChanged();
    partial void OnMauSacChanging(string value);
    partial void OnMauSacChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    partial void OnChatLieuChanging(string value);
    partial void OnChatLieuChanged();
    partial void OnBaoHanhChanging(string value);
    partial void OnBaoHanhChanged();
    partial void OnDieuKienChanging(string value);
    partial void OnDieuKienChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnNgayKyGuiChanging(System.DateTime value);
    partial void OnNgayKyGuiChanged();
    partial void OnThoiGianGuiChanging(string value);
    partial void OnThoiGianGuiChanged();
    partial void OnPhiKyGuiChanging(double value);
    partial void OnPhiKyGuiChanged();
    partial void OnDonGiaNhapChanging(double value);
    partial void OnDonGiaNhapChanged();
    #endregion
		
		public DANH_SACH_KY_GUI_CHO()
		{
			this._KHACH_HANG = default(EntityRef<KHACH_HANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KHACH_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGiay", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenGiay
		{
			get
			{
				return this._TenGiay;
			}
			set
			{
				if ((this._TenGiay != value))
				{
					this.OnTenGiayChanging(value);
					this.SendPropertyChanging();
					this._TenGiay = value;
					this.SendPropertyChanged("TenGiay");
					this.OnTenGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh1", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Anh1
		{
			get
			{
				return this._Anh1;
			}
			set
			{
				if ((this._Anh1 != value))
				{
					this.OnAnh1Changing(value);
					this.SendPropertyChanging();
					this._Anh1 = value;
					this.SendPropertyChanged("Anh1");
					this.OnAnh1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh2", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Anh2
		{
			get
			{
				return this._Anh2;
			}
			set
			{
				if ((this._Anh2 != value))
				{
					this.OnAnh2Changing(value);
					this.SendPropertyChanging();
					this._Anh2 = value;
					this.SendPropertyChanged("Anh2");
					this.OnAnh2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh3", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Anh3
		{
			get
			{
				return this._Anh3;
			}
			set
			{
				if ((this._Anh3 != value))
				{
					this.OnAnh3Changing(value);
					this.SendPropertyChanging();
					this._Anh3 = value;
					this.SendPropertyChanged("Anh3");
					this.OnAnh3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh4", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Anh4
		{
			get
			{
				return this._Anh4;
			}
			set
			{
				if ((this._Anh4 != value))
				{
					this.OnAnh4Changing(value);
					this.SendPropertyChanging();
					this._Anh4 = value;
					this.SendPropertyChanged("Anh4");
					this.OnAnh4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Float NOT NULL")]
		public double SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MauSac", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MauSac
		{
			get
			{
				return this._MauSac;
			}
			set
			{
				if ((this._MauSac != value))
				{
					this.OnMauSacChanging(value);
					this.SendPropertyChanging();
					this._MauSac = value;
					this.SendPropertyChanged("MauSac");
					this.OnMauSacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="Char(53) NOT NULL", CanBeNull=false)]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChatLieu", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string ChatLieu
		{
			get
			{
				return this._ChatLieu;
			}
			set
			{
				if ((this._ChatLieu != value))
				{
					this.OnChatLieuChanging(value);
					this.SendPropertyChanging();
					this._ChatLieu = value;
					this.SendPropertyChanged("ChatLieu");
					this.OnChatLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaoHanh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BaoHanh
		{
			get
			{
				return this._BaoHanh;
			}
			set
			{
				if ((this._BaoHanh != value))
				{
					this.OnBaoHanhChanging(value);
					this.SendPropertyChanging();
					this._BaoHanh = value;
					this.SendPropertyChanged("BaoHanh");
					this.OnBaoHanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DieuKien", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string DieuKien
		{
			get
			{
				return this._DieuKien;
			}
			set
			{
				if ((this._DieuKien != value))
				{
					this.OnDieuKienChanging(value);
					this.SendPropertyChanging();
					this._DieuKien = value;
					this.SendPropertyChanged("DieuKien");
					this.OnDieuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(2000)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKyGui", DbType="Date NOT NULL")]
		public System.DateTime NgayKyGui
		{
			get
			{
				return this._NgayKyGui;
			}
			set
			{
				if ((this._NgayKyGui != value))
				{
					this.OnNgayKyGuiChanging(value);
					this.SendPropertyChanging();
					this._NgayKyGui = value;
					this.SendPropertyChanged("NgayKyGui");
					this.OnNgayKyGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianGui", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ThoiGianGui
		{
			get
			{
				return this._ThoiGianGui;
			}
			set
			{
				if ((this._ThoiGianGui != value))
				{
					this.OnThoiGianGuiChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianGui = value;
					this.SendPropertyChanged("ThoiGianGui");
					this.OnThoiGianGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiKyGui", DbType="Float NOT NULL")]
		public double PhiKyGui
		{
			get
			{
				return this._PhiKyGui;
			}
			set
			{
				if ((this._PhiKyGui != value))
				{
					this.OnPhiKyGuiChanging(value);
					this.SendPropertyChanging();
					this._PhiKyGui = value;
					this.SendPropertyChanged("PhiKyGui");
					this.OnPhiKyGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaNhap", DbType="Float NOT NULL")]
		public double DonGiaNhap
		{
			get
			{
				return this._DonGiaNhap;
			}
			set
			{
				if ((this._DonGiaNhap != value))
				{
					this.OnDonGiaNhapChanging(value);
					this.SendPropertyChanging();
					this._DonGiaNhap = value;
					this.SendPropertyChanged("DonGiaNhap");
					this.OnDonGiaNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_DANH_SACH_KY_GUI_CHO", Storage="_KHACH_HANG", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KHACH_HANG KHACH_HANG
		{
			get
			{
				return this._KHACH_HANG.Entity;
			}
			set
			{
				KHACH_HANG previousValue = this._KHACH_HANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACH_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACH_HANG.Entity = null;
						previousValue.DANH_SACH_KY_GUI_CHO = null;
					}
					this._KHACH_HANG.Entity = value;
					if ((value != null))
					{
						value.DANH_SACH_KY_GUI_CHO = this;
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("KHACH_HANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIO_HANG")]
	public partial class GIO_HANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGioHang;
		
		private string _MaGiay;
		
		private string _MaKhachHang;
		
		private double _SoLuongDat;
		
		private string _SizeDat;
		
		private double _SoLuongMatHang;
		
		private string _SizeMatHang;
		
		private EntityRef<KHACH_HANG> _KHACH_HANG;
		
		private EntityRef<MAT_HANG> _MAT_HANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGioHangChanging(string value);
    partial void OnMaGioHangChanged();
    partial void OnMaGiayChanging(string value);
    partial void OnMaGiayChanged();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnSoLuongDatChanging(double value);
    partial void OnSoLuongDatChanged();
    partial void OnSizeDatChanging(string value);
    partial void OnSizeDatChanged();
    partial void OnSoLuongMatHangChanging(double value);
    partial void OnSoLuongMatHangChanged();
    partial void OnSizeMatHangChanging(string value);
    partial void OnSizeMatHangChanged();
    #endregion
		
		public GIO_HANG()
		{
			this._KHACH_HANG = default(EntityRef<KHACH_HANG>);
			this._MAT_HANG = default(EntityRef<MAT_HANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGioHang", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGioHang
		{
			get
			{
				return this._MaGioHang;
			}
			set
			{
				if ((this._MaGioHang != value))
				{
					this.OnMaGioHangChanging(value);
					this.SendPropertyChanging();
					this._MaGioHang = value;
					this.SendPropertyChanged("MaGioHang");
					this.OnMaGioHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiay", DbType="Char(20)")]
		public string MaGiay
		{
			get
			{
				return this._MaGiay;
			}
			set
			{
				if ((this._MaGiay != value))
				{
					if (this._MAT_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGiayChanging(value);
					this.SendPropertyChanging();
					this._MaGiay = value;
					this.SendPropertyChanged("MaGiay");
					this.OnMaGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Char(20)")]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KHACH_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongDat", DbType="Float NOT NULL")]
		public double SoLuongDat
		{
			get
			{
				return this._SoLuongDat;
			}
			set
			{
				if ((this._SoLuongDat != value))
				{
					this.OnSoLuongDatChanging(value);
					this.SendPropertyChanging();
					this._SoLuongDat = value;
					this.SendPropertyChanged("SoLuongDat");
					this.OnSoLuongDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SizeDat", DbType="Char(53) NOT NULL", CanBeNull=false)]
		public string SizeDat
		{
			get
			{
				return this._SizeDat;
			}
			set
			{
				if ((this._SizeDat != value))
				{
					this.OnSizeDatChanging(value);
					this.SendPropertyChanging();
					this._SizeDat = value;
					this.SendPropertyChanged("SizeDat");
					this.OnSizeDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongMatHang", DbType="Float NOT NULL")]
		public double SoLuongMatHang
		{
			get
			{
				return this._SoLuongMatHang;
			}
			set
			{
				if ((this._SoLuongMatHang != value))
				{
					this.OnSoLuongMatHangChanging(value);
					this.SendPropertyChanging();
					this._SoLuongMatHang = value;
					this.SendPropertyChanged("SoLuongMatHang");
					this.OnSoLuongMatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SizeMatHang", DbType="Char(53) NOT NULL", CanBeNull=false)]
		public string SizeMatHang
		{
			get
			{
				return this._SizeMatHang;
			}
			set
			{
				if ((this._SizeMatHang != value))
				{
					this.OnSizeMatHangChanging(value);
					this.SendPropertyChanging();
					this._SizeMatHang = value;
					this.SendPropertyChanged("SizeMatHang");
					this.OnSizeMatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_GIO_HANG", Storage="_KHACH_HANG", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KHACH_HANG KHACH_HANG
		{
			get
			{
				return this._KHACH_HANG.Entity;
			}
			set
			{
				KHACH_HANG previousValue = this._KHACH_HANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACH_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACH_HANG.Entity = null;
						previousValue.GIO_HANGs.Remove(this);
					}
					this._KHACH_HANG.Entity = value;
					if ((value != null))
					{
						value.GIO_HANGs.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("KHACH_HANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAT_HANG_GIO_HANG", Storage="_MAT_HANG", ThisKey="MaGiay", OtherKey="MaGiay", IsForeignKey=true)]
		public MAT_HANG MAT_HANG
		{
			get
			{
				return this._MAT_HANG.Entity;
			}
			set
			{
				MAT_HANG previousValue = this._MAT_HANG.Entity;
				if (((previousValue != value) 
							|| (this._MAT_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAT_HANG.Entity = null;
						previousValue.GIO_HANGs.Remove(this);
					}
					this._MAT_HANG.Entity = value;
					if ((value != null))
					{
						value.GIO_HANGs.Add(this);
						this._MaGiay = value.MaGiay;
					}
					else
					{
						this._MaGiay = default(string);
					}
					this.SendPropertyChanged("MAT_HANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOA_DON")]
	public partial class HOA_DON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoaDon;
		
		private string _MaGiay;
		
		private string _MaKhuyenMai;
		
		private string _PhuongThucThanhToan;
		
		private double _DonGiaBan;
		
		private string _KhuyenMai;
		
		private double _ThanhTien;
		
		private EntityRef<CHI_TIET_HOA_DON> _CHI_TIET_HOA_DON;
		
		private EntityRef<MAT_HANG> _MAT_HANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(string value);
    partial void OnMaHoaDonChanged();
    partial void OnMaGiayChanging(string value);
    partial void OnMaGiayChanged();
    partial void OnMaKhuyenMaiChanging(string value);
    partial void OnMaKhuyenMaiChanged();
    partial void OnPhuongThucThanhToanChanging(string value);
    partial void OnPhuongThucThanhToanChanged();
    partial void OnDonGiaBanChanging(double value);
    partial void OnDonGiaBanChanged();
    partial void OnKhuyenMaiChanging(string value);
    partial void OnKhuyenMaiChanged();
    partial void OnThanhTienChanging(double value);
    partial void OnThanhTienChanged();
    #endregion
		
		public HOA_DON()
		{
			this._CHI_TIET_HOA_DON = default(EntityRef<CHI_TIET_HOA_DON>);
			this._MAT_HANG = default(EntityRef<MAT_HANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="Char(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiay", DbType="Char(20)")]
		public string MaGiay
		{
			get
			{
				return this._MaGiay;
			}
			set
			{
				if ((this._MaGiay != value))
				{
					if (this._MAT_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGiayChanging(value);
					this.SendPropertyChanging();
					this._MaGiay = value;
					this.SendPropertyChanged("MaGiay");
					this.OnMaGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhuyenMai", DbType="Char(20)")]
		public string MaKhuyenMai
		{
			get
			{
				return this._MaKhuyenMai;
			}
			set
			{
				if ((this._MaKhuyenMai != value))
				{
					this.OnMaKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._MaKhuyenMai = value;
					this.SendPropertyChanged("MaKhuyenMai");
					this.OnMaKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongThucThanhToan", DbType="NChar(20)")]
		public string PhuongThucThanhToan
		{
			get
			{
				return this._PhuongThucThanhToan;
			}
			set
			{
				if ((this._PhuongThucThanhToan != value))
				{
					this.OnPhuongThucThanhToanChanging(value);
					this.SendPropertyChanging();
					this._PhuongThucThanhToan = value;
					this.SendPropertyChanged("PhuongThucThanhToan");
					this.OnPhuongThucThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaBan", DbType="Float NOT NULL")]
		public double DonGiaBan
		{
			get
			{
				return this._DonGiaBan;
			}
			set
			{
				if ((this._DonGiaBan != value))
				{
					this.OnDonGiaBanChanging(value);
					this.SendPropertyChanging();
					this._DonGiaBan = value;
					this.SendPropertyChanged("DonGiaBan");
					this.OnDonGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhuyenMai", DbType="Char(53) NOT NULL", CanBeNull=false)]
		public string KhuyenMai
		{
			get
			{
				return this._KhuyenMai;
			}
			set
			{
				if ((this._KhuyenMai != value))
				{
					this.OnKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._KhuyenMai = value;
					this.SendPropertyChanged("KhuyenMai");
					this.OnKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Float NOT NULL")]
		public double ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOA_DON_CHI_TIET_HOA_DON", Storage="_CHI_TIET_HOA_DON", ThisKey="MaHoaDon", OtherKey="MaHoaDon", IsUnique=true, IsForeignKey=false)]
		public CHI_TIET_HOA_DON CHI_TIET_HOA_DON
		{
			get
			{
				return this._CHI_TIET_HOA_DON.Entity;
			}
			set
			{
				CHI_TIET_HOA_DON previousValue = this._CHI_TIET_HOA_DON.Entity;
				if (((previousValue != value) 
							|| (this._CHI_TIET_HOA_DON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHI_TIET_HOA_DON.Entity = null;
						previousValue.HOA_DON = null;
					}
					this._CHI_TIET_HOA_DON.Entity = value;
					if ((value != null))
					{
						value.HOA_DON = this;
					}
					this.SendPropertyChanged("CHI_TIET_HOA_DON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAT_HANG_HOA_DON", Storage="_MAT_HANG", ThisKey="MaGiay", OtherKey="MaGiay", IsForeignKey=true)]
		public MAT_HANG MAT_HANG
		{
			get
			{
				return this._MAT_HANG.Entity;
			}
			set
			{
				MAT_HANG previousValue = this._MAT_HANG.Entity;
				if (((previousValue != value) 
							|| (this._MAT_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAT_HANG.Entity = null;
						previousValue.HOA_DONs.Remove(this);
					}
					this._MAT_HANG.Entity = value;
					if ((value != null))
					{
						value.HOA_DONs.Add(this);
						this._MaGiay = value.MaGiay;
					}
					else
					{
						this._MaGiay = default(string);
					}
					this.SendPropertyChanged("MAT_HANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACH_HANG")]
	public partial class KHACH_HANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhachHang;
		
		private string _TenKhachHang;
		
		private string _SoDienThoai;
		
		private string _DiaChi;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _GioiTinh;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _GhiChu;
		
		private double _TienVDT;
		
		private string _MaBaoMat;
		
		private EntitySet<CHI_TIET_HOA_DON> _CHI_TIET_HOA_DONs;
		
		private EntitySet<DANH_SACH_HOA_DON_CHO> _DANH_SACH_HOA_DON_CHOs;
		
		private EntityRef<DANH_SACH_KY_GUI_CHO> _DANH_SACH_KY_GUI_CHO;
		
		private EntitySet<GIO_HANG> _GIO_HANGs;
		
		private EntitySet<KY_GUI> _KY_GUIs;
		
		private EntitySet<PAYPAL> _PAYPALs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnTenKhachHangChanging(string value);
    partial void OnTenKhachHangChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnTienVDTChanging(double value);
    partial void OnTienVDTChanged();
    partial void OnMaBaoMatChanging(string value);
    partial void OnMaBaoMatChanged();
    #endregion
		
		public KHACH_HANG()
		{
			this._CHI_TIET_HOA_DONs = new EntitySet<CHI_TIET_HOA_DON>(new Action<CHI_TIET_HOA_DON>(this.attach_CHI_TIET_HOA_DONs), new Action<CHI_TIET_HOA_DON>(this.detach_CHI_TIET_HOA_DONs));
			this._DANH_SACH_HOA_DON_CHOs = new EntitySet<DANH_SACH_HOA_DON_CHO>(new Action<DANH_SACH_HOA_DON_CHO>(this.attach_DANH_SACH_HOA_DON_CHOs), new Action<DANH_SACH_HOA_DON_CHO>(this.detach_DANH_SACH_HOA_DON_CHOs));
			this._DANH_SACH_KY_GUI_CHO = default(EntityRef<DANH_SACH_KY_GUI_CHO>);
			this._GIO_HANGs = new EntitySet<GIO_HANG>(new Action<GIO_HANG>(this.attach_GIO_HANGs), new Action<GIO_HANG>(this.detach_GIO_HANGs));
			this._KY_GUIs = new EntitySet<KY_GUI>(new Action<KY_GUI>(this.attach_KY_GUIs), new Action<KY_GUI>(this.detach_KY_GUIs));
			this._PAYPALs = new EntitySet<PAYPAL>(new Action<PAYPAL>(this.attach_PAYPALs), new Action<PAYPAL>(this.detach_PAYPALs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this.OnTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenKhachHang = value;
					this.SendPropertyChanged("TenKhachHang");
					this.OnTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="Char(10)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NChar(4)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NChar(5)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienVDT", DbType="Float NOT NULL")]
		public double TienVDT
		{
			get
			{
				return this._TienVDT;
			}
			set
			{
				if ((this._TienVDT != value))
				{
					this.OnTienVDTChanging(value);
					this.SendPropertyChanging();
					this._TienVDT = value;
					this.SendPropertyChanged("TienVDT");
					this.OnTienVDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaoMat", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MaBaoMat
		{
			get
			{
				return this._MaBaoMat;
			}
			set
			{
				if ((this._MaBaoMat != value))
				{
					this.OnMaBaoMatChanging(value);
					this.SendPropertyChanging();
					this._MaBaoMat = value;
					this.SendPropertyChanged("MaBaoMat");
					this.OnMaBaoMatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_CHI_TIET_HOA_DON", Storage="_CHI_TIET_HOA_DONs", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<CHI_TIET_HOA_DON> CHI_TIET_HOA_DONs
		{
			get
			{
				return this._CHI_TIET_HOA_DONs;
			}
			set
			{
				this._CHI_TIET_HOA_DONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_DANH_SACH_HOA_DON_CHO", Storage="_DANH_SACH_HOA_DON_CHOs", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<DANH_SACH_HOA_DON_CHO> DANH_SACH_HOA_DON_CHOs
		{
			get
			{
				return this._DANH_SACH_HOA_DON_CHOs;
			}
			set
			{
				this._DANH_SACH_HOA_DON_CHOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_DANH_SACH_KY_GUI_CHO", Storage="_DANH_SACH_KY_GUI_CHO", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsUnique=true, IsForeignKey=false)]
		public DANH_SACH_KY_GUI_CHO DANH_SACH_KY_GUI_CHO
		{
			get
			{
				return this._DANH_SACH_KY_GUI_CHO.Entity;
			}
			set
			{
				DANH_SACH_KY_GUI_CHO previousValue = this._DANH_SACH_KY_GUI_CHO.Entity;
				if (((previousValue != value) 
							|| (this._DANH_SACH_KY_GUI_CHO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANH_SACH_KY_GUI_CHO.Entity = null;
						previousValue.KHACH_HANG = null;
					}
					this._DANH_SACH_KY_GUI_CHO.Entity = value;
					if ((value != null))
					{
						value.KHACH_HANG = this;
					}
					this.SendPropertyChanged("DANH_SACH_KY_GUI_CHO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_GIO_HANG", Storage="_GIO_HANGs", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<GIO_HANG> GIO_HANGs
		{
			get
			{
				return this._GIO_HANGs;
			}
			set
			{
				this._GIO_HANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_KY_GUI", Storage="_KY_GUIs", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<KY_GUI> KY_GUIs
		{
			get
			{
				return this._KY_GUIs;
			}
			set
			{
				this._KY_GUIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_PAYPAL", Storage="_PAYPALs", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<PAYPAL> PAYPALs
		{
			get
			{
				return this._PAYPALs;
			}
			set
			{
				this._PAYPALs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHI_TIET_HOA_DONs(CHI_TIET_HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = this;
		}
		
		private void detach_CHI_TIET_HOA_DONs(CHI_TIET_HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = null;
		}
		
		private void attach_DANH_SACH_HOA_DON_CHOs(DANH_SACH_HOA_DON_CHO entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = this;
		}
		
		private void detach_DANH_SACH_HOA_DON_CHOs(DANH_SACH_HOA_DON_CHO entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = null;
		}
		
		private void attach_GIO_HANGs(GIO_HANG entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = this;
		}
		
		private void detach_GIO_HANGs(GIO_HANG entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = null;
		}
		
		private void attach_KY_GUIs(KY_GUI entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = this;
		}
		
		private void detach_KY_GUIs(KY_GUI entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = null;
		}
		
		private void attach_PAYPALs(PAYPAL entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = this;
		}
		
		private void detach_PAYPALs(PAYPAL entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KY_GUI")]
	public partial class KY_GUI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGiay;
		
		private string _MaKhachHang;
		
		private string _MaNhanVien;
		
		private System.DateTime _NgayKyGui;
		
		private string _ThoiGianGui;
		
		private double _PhiKyGui;
		
		private double _DonGiaNhap;
		
		private EntityRef<KHACH_HANG> _KHACH_HANG;
		
		private EntityRef<MAT_HANG> _MAT_HANG;
		
		private EntityRef<NHAN_VIEN> _NHAN_VIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGiayChanging(string value);
    partial void OnMaGiayChanged();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnNgayKyGuiChanging(System.DateTime value);
    partial void OnNgayKyGuiChanged();
    partial void OnThoiGianGuiChanging(string value);
    partial void OnThoiGianGuiChanged();
    partial void OnPhiKyGuiChanging(double value);
    partial void OnPhiKyGuiChanged();
    partial void OnDonGiaNhapChanging(double value);
    partial void OnDonGiaNhapChanged();
    #endregion
		
		public KY_GUI()
		{
			this._KHACH_HANG = default(EntityRef<KHACH_HANG>);
			this._MAT_HANG = default(EntityRef<MAT_HANG>);
			this._NHAN_VIEN = default(EntityRef<NHAN_VIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiay", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGiay
		{
			get
			{
				return this._MaGiay;
			}
			set
			{
				if ((this._MaGiay != value))
				{
					if (this._MAT_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGiayChanging(value);
					this.SendPropertyChanging();
					this._MaGiay = value;
					this.SendPropertyChanged("MaGiay");
					this.OnMaGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KHACH_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NHAN_VIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKyGui", DbType="Date NOT NULL")]
		public System.DateTime NgayKyGui
		{
			get
			{
				return this._NgayKyGui;
			}
			set
			{
				if ((this._NgayKyGui != value))
				{
					this.OnNgayKyGuiChanging(value);
					this.SendPropertyChanging();
					this._NgayKyGui = value;
					this.SendPropertyChanged("NgayKyGui");
					this.OnNgayKyGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianGui", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ThoiGianGui
		{
			get
			{
				return this._ThoiGianGui;
			}
			set
			{
				if ((this._ThoiGianGui != value))
				{
					this.OnThoiGianGuiChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianGui = value;
					this.SendPropertyChanged("ThoiGianGui");
					this.OnThoiGianGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiKyGui", DbType="Float NOT NULL")]
		public double PhiKyGui
		{
			get
			{
				return this._PhiKyGui;
			}
			set
			{
				if ((this._PhiKyGui != value))
				{
					this.OnPhiKyGuiChanging(value);
					this.SendPropertyChanging();
					this._PhiKyGui = value;
					this.SendPropertyChanged("PhiKyGui");
					this.OnPhiKyGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaNhap", DbType="Float NOT NULL")]
		public double DonGiaNhap
		{
			get
			{
				return this._DonGiaNhap;
			}
			set
			{
				if ((this._DonGiaNhap != value))
				{
					this.OnDonGiaNhapChanging(value);
					this.SendPropertyChanging();
					this._DonGiaNhap = value;
					this.SendPropertyChanged("DonGiaNhap");
					this.OnDonGiaNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_KY_GUI", Storage="_KHACH_HANG", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KHACH_HANG KHACH_HANG
		{
			get
			{
				return this._KHACH_HANG.Entity;
			}
			set
			{
				KHACH_HANG previousValue = this._KHACH_HANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACH_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACH_HANG.Entity = null;
						previousValue.KY_GUIs.Remove(this);
					}
					this._KHACH_HANG.Entity = value;
					if ((value != null))
					{
						value.KY_GUIs.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("KHACH_HANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAT_HANG_KY_GUI", Storage="_MAT_HANG", ThisKey="MaGiay", OtherKey="MaGiay", IsForeignKey=true)]
		public MAT_HANG MAT_HANG
		{
			get
			{
				return this._MAT_HANG.Entity;
			}
			set
			{
				MAT_HANG previousValue = this._MAT_HANG.Entity;
				if (((previousValue != value) 
							|| (this._MAT_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAT_HANG.Entity = null;
						previousValue.KY_GUIs.Remove(this);
					}
					this._MAT_HANG.Entity = value;
					if ((value != null))
					{
						value.KY_GUIs.Add(this);
						this._MaGiay = value.MaGiay;
					}
					else
					{
						this._MaGiay = default(string);
					}
					this.SendPropertyChanged("MAT_HANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHAN_VIEN_KY_GUI", Storage="_NHAN_VIEN", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NHAN_VIEN NHAN_VIEN
		{
			get
			{
				return this._NHAN_VIEN.Entity;
			}
			set
			{
				NHAN_VIEN previousValue = this._NHAN_VIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHAN_VIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHAN_VIEN.Entity = null;
						previousValue.KY_GUIs.Remove(this);
					}
					this._NHAN_VIEN.Entity = value;
					if ((value != null))
					{
						value.KY_GUIs.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("NHAN_VIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAT_HANG")]
	public partial class MAT_HANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGiay;
		
		private string _TenGiay;
		
		private System.Data.Linq.Binary _Anh1;
		
		private System.Data.Linq.Binary _Anh2;
		
		private System.Data.Linq.Binary _Anh3;
		
		private System.Data.Linq.Binary _Anh4;
		
		private string _Loai;
		
		private double _SoLuong;
		
		private string _MauSac;
		
		private string _Size;
		
		private double _DonGiaBan;
		
		private EntityRef<CHI_TIET_MAT_HANG> _CHI_TIET_MAT_HANG;
		
		private EntitySet<DANH_SACH_HOA_DON_CHO> _DANH_SACH_HOA_DON_CHOs;
		
		private EntitySet<GIO_HANG> _GIO_HANGs;
		
		private EntitySet<HOA_DON> _HOA_DONs;
		
		private EntitySet<KY_GUI> _KY_GUIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGiayChanging(string value);
    partial void OnMaGiayChanged();
    partial void OnTenGiayChanging(string value);
    partial void OnTenGiayChanged();
    partial void OnAnh1Changing(System.Data.Linq.Binary value);
    partial void OnAnh1Changed();
    partial void OnAnh2Changing(System.Data.Linq.Binary value);
    partial void OnAnh2Changed();
    partial void OnAnh3Changing(System.Data.Linq.Binary value);
    partial void OnAnh3Changed();
    partial void OnAnh4Changing(System.Data.Linq.Binary value);
    partial void OnAnh4Changed();
    partial void OnLoaiChanging(string value);
    partial void OnLoaiChanged();
    partial void OnSoLuongChanging(double value);
    partial void OnSoLuongChanged();
    partial void OnMauSacChanging(string value);
    partial void OnMauSacChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    partial void OnDonGiaBanChanging(double value);
    partial void OnDonGiaBanChanged();
    #endregion
		
		public MAT_HANG()
		{
			this._CHI_TIET_MAT_HANG = default(EntityRef<CHI_TIET_MAT_HANG>);
			this._DANH_SACH_HOA_DON_CHOs = new EntitySet<DANH_SACH_HOA_DON_CHO>(new Action<DANH_SACH_HOA_DON_CHO>(this.attach_DANH_SACH_HOA_DON_CHOs), new Action<DANH_SACH_HOA_DON_CHO>(this.detach_DANH_SACH_HOA_DON_CHOs));
			this._GIO_HANGs = new EntitySet<GIO_HANG>(new Action<GIO_HANG>(this.attach_GIO_HANGs), new Action<GIO_HANG>(this.detach_GIO_HANGs));
			this._HOA_DONs = new EntitySet<HOA_DON>(new Action<HOA_DON>(this.attach_HOA_DONs), new Action<HOA_DON>(this.detach_HOA_DONs));
			this._KY_GUIs = new EntitySet<KY_GUI>(new Action<KY_GUI>(this.attach_KY_GUIs), new Action<KY_GUI>(this.detach_KY_GUIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiay", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGiay
		{
			get
			{
				return this._MaGiay;
			}
			set
			{
				if ((this._MaGiay != value))
				{
					this.OnMaGiayChanging(value);
					this.SendPropertyChanging();
					this._MaGiay = value;
					this.SendPropertyChanged("MaGiay");
					this.OnMaGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGiay", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenGiay
		{
			get
			{
				return this._TenGiay;
			}
			set
			{
				if ((this._TenGiay != value))
				{
					this.OnTenGiayChanging(value);
					this.SendPropertyChanging();
					this._TenGiay = value;
					this.SendPropertyChanged("TenGiay");
					this.OnTenGiayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh1", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Anh1
		{
			get
			{
				return this._Anh1;
			}
			set
			{
				if ((this._Anh1 != value))
				{
					this.OnAnh1Changing(value);
					this.SendPropertyChanging();
					this._Anh1 = value;
					this.SendPropertyChanged("Anh1");
					this.OnAnh1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh2", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Anh2
		{
			get
			{
				return this._Anh2;
			}
			set
			{
				if ((this._Anh2 != value))
				{
					this.OnAnh2Changing(value);
					this.SendPropertyChanging();
					this._Anh2 = value;
					this.SendPropertyChanged("Anh2");
					this.OnAnh2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh3", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Anh3
		{
			get
			{
				return this._Anh3;
			}
			set
			{
				if ((this._Anh3 != value))
				{
					this.OnAnh3Changing(value);
					this.SendPropertyChanging();
					this._Anh3 = value;
					this.SendPropertyChanged("Anh3");
					this.OnAnh3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh4", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Anh4
		{
			get
			{
				return this._Anh4;
			}
			set
			{
				if ((this._Anh4 != value))
				{
					this.OnAnh4Changing(value);
					this.SendPropertyChanging();
					this._Anh4 = value;
					this.SendPropertyChanged("Anh4");
					this.OnAnh4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="NChar(3)")]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Float NOT NULL")]
		public double SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MauSac", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MauSac
		{
			get
			{
				return this._MauSac;
			}
			set
			{
				if ((this._MauSac != value))
				{
					this.OnMauSacChanging(value);
					this.SendPropertyChanging();
					this._MauSac = value;
					this.SendPropertyChanged("MauSac");
					this.OnMauSacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="Char(53) NOT NULL", CanBeNull=false)]
		public string Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaBan", DbType="Float NOT NULL")]
		public double DonGiaBan
		{
			get
			{
				return this._DonGiaBan;
			}
			set
			{
				if ((this._DonGiaBan != value))
				{
					this.OnDonGiaBanChanging(value);
					this.SendPropertyChanging();
					this._DonGiaBan = value;
					this.SendPropertyChanged("DonGiaBan");
					this.OnDonGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAT_HANG_CHI_TIET_MAT_HANG", Storage="_CHI_TIET_MAT_HANG", ThisKey="MaGiay", OtherKey="MaGiay", IsUnique=true, IsForeignKey=false)]
		public CHI_TIET_MAT_HANG CHI_TIET_MAT_HANG
		{
			get
			{
				return this._CHI_TIET_MAT_HANG.Entity;
			}
			set
			{
				CHI_TIET_MAT_HANG previousValue = this._CHI_TIET_MAT_HANG.Entity;
				if (((previousValue != value) 
							|| (this._CHI_TIET_MAT_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHI_TIET_MAT_HANG.Entity = null;
						previousValue.MAT_HANG = null;
					}
					this._CHI_TIET_MAT_HANG.Entity = value;
					if ((value != null))
					{
						value.MAT_HANG = this;
					}
					this.SendPropertyChanged("CHI_TIET_MAT_HANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAT_HANG_DANH_SACH_HOA_DON_CHO", Storage="_DANH_SACH_HOA_DON_CHOs", ThisKey="MaGiay", OtherKey="MaGiay")]
		public EntitySet<DANH_SACH_HOA_DON_CHO> DANH_SACH_HOA_DON_CHOs
		{
			get
			{
				return this._DANH_SACH_HOA_DON_CHOs;
			}
			set
			{
				this._DANH_SACH_HOA_DON_CHOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAT_HANG_GIO_HANG", Storage="_GIO_HANGs", ThisKey="MaGiay", OtherKey="MaGiay")]
		public EntitySet<GIO_HANG> GIO_HANGs
		{
			get
			{
				return this._GIO_HANGs;
			}
			set
			{
				this._GIO_HANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAT_HANG_HOA_DON", Storage="_HOA_DONs", ThisKey="MaGiay", OtherKey="MaGiay")]
		public EntitySet<HOA_DON> HOA_DONs
		{
			get
			{
				return this._HOA_DONs;
			}
			set
			{
				this._HOA_DONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAT_HANG_KY_GUI", Storage="_KY_GUIs", ThisKey="MaGiay", OtherKey="MaGiay")]
		public EntitySet<KY_GUI> KY_GUIs
		{
			get
			{
				return this._KY_GUIs;
			}
			set
			{
				this._KY_GUIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANH_SACH_HOA_DON_CHOs(DANH_SACH_HOA_DON_CHO entity)
		{
			this.SendPropertyChanging();
			entity.MAT_HANG = this;
		}
		
		private void detach_DANH_SACH_HOA_DON_CHOs(DANH_SACH_HOA_DON_CHO entity)
		{
			this.SendPropertyChanging();
			entity.MAT_HANG = null;
		}
		
		private void attach_GIO_HANGs(GIO_HANG entity)
		{
			this.SendPropertyChanging();
			entity.MAT_HANG = this;
		}
		
		private void detach_GIO_HANGs(GIO_HANG entity)
		{
			this.SendPropertyChanging();
			entity.MAT_HANG = null;
		}
		
		private void attach_HOA_DONs(HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.MAT_HANG = this;
		}
		
		private void detach_HOA_DONs(HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.MAT_HANG = null;
		}
		
		private void attach_KY_GUIs(KY_GUI entity)
		{
			this.SendPropertyChanging();
			entity.MAT_HANG = this;
		}
		
		private void detach_KY_GUIs(KY_GUI entity)
		{
			this.SendPropertyChanging();
			entity.MAT_HANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHAN_VIEN")]
	public partial class NHAN_VIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanVien;
		
		private string _TenNhanVien;
		
		private string _SoDienThoai;
		
		private string _DiaChi;
		
		private System.DateTime _NgaySinh;
		
		private string _GioiTinh;
		
		private EntitySet<CHI_TIET_HOA_DON> _CHI_TIET_HOA_DONs;
		
		private EntitySet<KY_GUI> _KY_GUIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnTenNhanVienChanging(string value);
    partial void OnTenNhanVienChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    #endregion
		
		public NHAN_VIEN()
		{
			this._CHI_TIET_HOA_DONs = new EntitySet<CHI_TIET_HOA_DON>(new Action<CHI_TIET_HOA_DON>(this.attach_CHI_TIET_HOA_DONs), new Action<CHI_TIET_HOA_DON>(this.detach_CHI_TIET_HOA_DONs));
			this._KY_GUIs = new EntitySet<KY_GUI>(new Action<KY_GUI>(this.attach_KY_GUIs), new Action<KY_GUI>(this.detach_KY_GUIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhanVien", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNhanVien
		{
			get
			{
				return this._TenNhanVien;
			}
			set
			{
				if ((this._TenNhanVien != value))
				{
					this.OnTenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._TenNhanVien = value;
					this.SendPropertyChanged("TenNhanVien");
					this.OnTenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NChar(4)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHAN_VIEN_CHI_TIET_HOA_DON", Storage="_CHI_TIET_HOA_DONs", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<CHI_TIET_HOA_DON> CHI_TIET_HOA_DONs
		{
			get
			{
				return this._CHI_TIET_HOA_DONs;
			}
			set
			{
				this._CHI_TIET_HOA_DONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHAN_VIEN_KY_GUI", Storage="_KY_GUIs", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<KY_GUI> KY_GUIs
		{
			get
			{
				return this._KY_GUIs;
			}
			set
			{
				this._KY_GUIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHI_TIET_HOA_DONs(CHI_TIET_HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.NHAN_VIEN = this;
		}
		
		private void detach_CHI_TIET_HOA_DONs(CHI_TIET_HOA_DON entity)
		{
			this.SendPropertyChanging();
			entity.NHAN_VIEN = null;
		}
		
		private void attach_KY_GUIs(KY_GUI entity)
		{
			this.SendPropertyChanging();
			entity.NHAN_VIEN = this;
		}
		
		private void detach_KY_GUIs(KY_GUI entity)
		{
			this.SendPropertyChanging();
			entity.NHAN_VIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PAYPAL")]
	public partial class PAYPAL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTaiKhoan;
		
		private string _MaKhachHang;
		
		private double _Tien;
		
		private string _MaBaoMat;
		
		private EntityRef<KHACH_HANG> _KHACH_HANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTaiKhoanChanging(string value);
    partial void OnMaTaiKhoanChanged();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnTienChanging(double value);
    partial void OnTienChanged();
    partial void OnMaBaoMatChanging(string value);
    partial void OnMaBaoMatChanged();
    #endregion
		
		public PAYPAL()
		{
			this._KHACH_HANG = default(EntityRef<KHACH_HANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiKhoan", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTaiKhoan
		{
			get
			{
				return this._MaTaiKhoan;
			}
			set
			{
				if ((this._MaTaiKhoan != value))
				{
					this.OnMaTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._MaTaiKhoan = value;
					this.SendPropertyChanged("MaTaiKhoan");
					this.OnMaTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Char(20)")]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KHACH_HANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tien", DbType="Float NOT NULL")]
		public double Tien
		{
			get
			{
				return this._Tien;
			}
			set
			{
				if ((this._Tien != value))
				{
					this.OnTienChanging(value);
					this.SendPropertyChanging();
					this._Tien = value;
					this.SendPropertyChanged("Tien");
					this.OnTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaoMat", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MaBaoMat
		{
			get
			{
				return this._MaBaoMat;
			}
			set
			{
				if ((this._MaBaoMat != value))
				{
					this.OnMaBaoMatChanging(value);
					this.SendPropertyChanging();
					this._MaBaoMat = value;
					this.SendPropertyChanged("MaBaoMat");
					this.OnMaBaoMatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_PAYPAL", Storage="_KHACH_HANG", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KHACH_HANG KHACH_HANG
		{
			get
			{
				return this._KHACH_HANG.Entity;
			}
			set
			{
				KHACH_HANG previousValue = this._KHACH_HANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACH_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACH_HANG.Entity = null;
						previousValue.PAYPALs.Remove(this);
					}
					this._KHACH_HANG.Entity = value;
					if ((value != null))
					{
						value.PAYPALs.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("KHACH_HANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
